categories = {
	"Subsystem": {
		"Engineering Systems": 364,
		"Propulsion Systems": 362,
		"Defensive Systems": 358,
		"Offensive Systems": 363,
		"Electronic Systems": 361,
	},
	"Celestial": {
		"Audit Log Secure Container": 232,
		"Wreck": 81,
		"Sun": 0,
		"Station Improvement Platform": 325,
		"Moon": 2,
		"Covert Beacon": 351,
		"Satellite": 380,
		"Force Field": 201,
		"Secure Cargo Container": 83,
		"Construction Platform": 115,
		"Beacon": 121,
		"Harvestable Cloud": 312,
		"Shipping Crates": 167,
		"Secondary Sun": 41,
		"Mobile Sentry Gun": 122,
		"Wormhole": 374,
		"Agents in Space": 42,
		"Planet": 1,
		"Stargate": 3,
		"Cargo Container": 4,
		"Destructible Station Services": 345,
		"Comet": 310,
		"Effect Beacon": 80,
		"Cosmic Anomaly": 349,
		"Freight Container": 84,
		"Biomass": 5,
		"Warp Gate": 100,
		"Cosmic Signature": 246,
		"Asteroid Belt": 237,
		"Large Collidable Object": 46,
		"Station Upgrade Platform": 324,
		"Cloud": 76,
	},
	"Drone": {
		"Electronic Warfare Drone": 288,
		"Warp Scrambling Drone": 264,
		"Mining Drone": 32,
		"Stasis Webifying Drone": 290,
		"Fighter Bomber": 79,
		"Repair Drone": 108,
		"Fighter Drone": 267,
		"Logistic Drone": 265,
		"Cap Drain Drone": 263,
		"Salvage Drone": 379,
		"Combat Drone": 31,
		"Unanchoring Drone": 234,
	},
	"Commodity": {
		"Commodities": 250,
		"Miscellaneous": 63,
	},
	"Accessories": {
		"Outpost Upgrades": 346,
		"Outpost Improvements": 344,
	},
	"Module": {
		"Smart Bomb": 33,
		"Projectile Weapon": 17,
		"Missile Launcher Bomb": 102,
		"Strip Miner": 210,
		"Mining Laser": 16,
		"Missile Launcher Heavy": 19,
		"Salvager": 321,
		"Energy Weapon": 15,
		"Missile Launcher Cruise": 169,
		"Missile Launcher Rocket": 119,
		"Festival Launcher": 244,
		"Missile Launcher Rapid Light": 36,
		"Missile Launcher Heavy Assault": 247,
		"Tractor Beam": 101,
		"Missile Launcher Light": 18,
		"Missile Launcher Citadel": 87,
		"Gas Cloud Harvester": 311,
		"Hybrid Weapon": 21,
		"Frequency Mining Laser": 240,
		"Countermeasure Launcher": 120,
		"Missile Launcher Torpedo": 20,
		"QA Module": 242,
	},
	"Entity": {
		"Asteroid Guristas Officer": 181,
		"Mission Generic Battleships": 160,
		"Customs Official": 231,
		"Mission Faction Battleship": 356,
		"Deadspace Blood Raiders Frigate": 211,
		"Mission Generic Frigates": 97,
		"Deadspace Sansha's Nation Battleship": 222,
		"Mission Gallente Federation Battlecruiser": 309,
		"Asteroid Guristas Cruiser": 61,
		"Asteroid Rogue Drone Destroyer": 318,
		"Destructible Sentry Gun": 168,
		"Incursion Sansha's Nation Battleship": 72,
		"Asteroid Angel Cartel Commander BattleCruiser": 271,
		"Deadspace Serpentis BattleCruiser": 300,
		"Asteroid Rogue Drone Officer": 386,
		"Mission Amarr Empire Cruiser": 139,
		"Deadspace Sansha's Nation Destroyer": 296,
		"FW Minmatar Republic Frigate": 382,
		"Asteroid Angel Cartel Battleship": 144,
		"Asteroid Blood Raiders Commander Destroyer": 274,
		"Deadspace Rogue Drone BattleCruiser": 90,
		"Mission Gallente Federation Battleship": 161,
		"Storyline Mission Battleship": 255,
		"Mission Caldari State Carrier": 332,
		"Storyline Battleship": 253,
		"Deadspace Sleeper Sleepless Patroller": 365,
		"Asteroid Sansha's Nation Commander Destroyer": 282,
		"Asteroid Sansha's Nation Destroyer": 280,
		"Mission Generic Battle Cruisers": 322,
		"Mission Amarr Empire Other": 313,
		"FW Gallente Federation Battlecruiser": 397,
		"Asteroid Guristas Commander Frigate": 179,
		"Spawn Container": 38,
		"Asteroid Sansha's Nation Frigate": 111,
		"Deadspace Rogue Drone Frigate": 88,
		"Asteroid Guristas Hauler": 193,
		"Asteroid Blood Raiders Officer": 177,
		"Mission Minmatar Republic Destroyer": 302,
		"FW Gallente Federation Frigate": 384,
		"Deadspace Blood Raiders BattleCruiser": 43,
		"Deadspace Sleeper Emergent Sentinel": 373,
		"Asteroid Angel Cartel Hauler": 190,
		"Asteroid Blood Raiders Commander Battleship": 176,
		"Convoy": 113,
		"Mission Khanid Cruiser": 150,
		"Storyline Mission Frigate": 257,
		"Mission Drone": 197,
		"Asteroid Rogue Drone Battleship": 319,
		"Asteroid Guristas Battleship": 148,
		"Mission Caldari State Other": 58,
		"Destructible Agents In Space": 256,
		"Asteroid Angel Cartel Destroyer": 268,
		"FW Gallente Federation Destroyer": 389,
		"Deadspace Angel Cartel Cruiser": 142,
		"FW Amarr Empire Frigate": 385,
		"Asteroid Guristas Frigate": 60,
		"Mission Amarr Empire Frigate": 135,
		"Asteroid Guristas Commander BattleCruiser": 279,
		"Deadspace Sleeper Sleepless Sentinel": 367,
		"Asteroid Serpentis Commander Battleship": 188,
		"Asteroid Rogue Drone Commander Cruiser": 337,
		"Mission Khanid Frigate": 149,
		"Mission Khanid Battleship": 163,
		"Mission Generic Cruisers": 131,
		"Asteroid Serpentis Cruiser": 59,
		"Mission Fighter Drone": 340,
		"Mission Mordu Cruiser": 199,
		"Deadspace Angel Cartel Frigate": 39,
		"Asteroid Sansha's Nation Cruiser": 112,
		"Asteroid Sansha's Nation Commander Cruiser": 182,
		"Deadspace Rogue Drone Cruiser": 89,
		"Asteroid Serpentis Frigate": 56,
		"Mission Caldari State Frigate": 136,
		"FW Caldari State Battlecruiser": 396,
		"Asteroid Sansha's Nation Officer": 184,
		"Mission Minmatar Republic Carrier": 334,
		"Asteroid Angel Cartel Commander Battleship": 172,
		"Asteroid Blood Raiders Battleship": 145,
		"Asteroid Rogue Drone Commander Destroyer": 338,
		"Mission CONCORD Battleship": 203,
		"Asteroid Blood Raiders Cruiser": 117,
		"Asteroid Rogue Drone Frigate": 316,
		"Deadspace Rogue Drone Battleship": 118,
		"Mission Caldari State Battlecruiser": 307,
		"Asteroid Sansha's Nation Hauler": 194,
		"Deadspace Guristas Destroyer": 295,
		"FW Caldari State Destroyer": 388,
		"Asteroid Sansha's Nation Commander Frigate": 185,
		"Asteroid Rogue Drone Hauler": 381,
		"Deadspace Blood Raiders Destroyer": 294,
		"Deadspace Serpentis Cruiser": 143,
		"Temporary Cloud": 130,
		"Asteroid Sansha's Nation Battleship": 146,
		"Asteroid Guristas Destroyer": 276,
		"Incursion Sansha's Nation Capital": 52,
		"Mini Container": 399,
		"FW Minmatar Republic Cruiser": 394,
		"Deadspace Overseer Battleship": 93,
		"Asteroid Blood Raiders Commander Frigate": 174,
		"FW Infrastructure Hub": 357,
		"Incursion Sansha's Nation Frigate": 50,
		"Mission Caldari State Battleship": 162,
		"Deadspace Angel Cartel BattleCruiser": 297,
		"Mission CONCORD Frigate": 40,
		"Asteroid Serpentis Battleship": 147,
		"Deadspace Blood Raiders Battleship": 219,
		"Deadspace Guristas BattleCruiser": 298,
		"Deadspace Guristas Frigate": 212,
		"Deadspace Overseer Frigate": 99,
		"Mission Amarr Empire Battlecruiser": 305,
		"Large Collidable Ship": 320,
		"Asteroid Angel Cartel Officer": 173,
		"Deadspace Overseer's Sentry": 92,
		"Storyline Frigate": 251,
		"Deadspace Serpentis Frigate": 48,
		"FW Minmatar Republic Destroyer": 390,
		"Deadspace Sleeper Awakened Defender": 369,
		"FW Minmatar Republic Battlecruiser": 398,
		"Asteroid Rogue Drone Cruiser": 314,
		"Mission Mordu Battleship": 200,
		"Convoy Drone": 107,
		"Asteroid Rogue Drone BattleCruiser": 317,
		"Deadspace Guristas Battleship": 220,
		"FW Gallente Federation Cruiser": 393,
		"FW Caldari State Cruiser": 392,
		"Deadspace Sansha's Nation Cruiser": 141,
		"Mission Amarr Empire Destroyer": 304,
		"Mission Caldari State Cruiser": 53,
		"Asteroid Serpentis BattleCruiser": 285,
		"Scatter Container": 258,
		"Mission Generic Destroyers": 323,
		"Deadspace Overseer's Belongings": 230,
		"Deadspace Rogue Drone Swarm": 124,
		"Asteroid Serpentis Commander Frigate": 187,
		"Mission Amarr Empire Battleship": 62,
		"Mission Gallente Federation Carrier": 333,
		"Mission Gallente Federation Frigate": 138,
		"Asteroid Blood Raiders Hauler": 191,
		"Deadspace Overseer Cruiser": 73,
		"Asteroid Angel Cartel Cruiser": 110,
		"Mission Thukker Frigate": 114,
		"Asteroid Blood Raiders Commander BattleCruiser": 275,
		"Asteroid Angel Cartel Commander Destroyer": 270,
		"Deadspace Angel Cartel Destroyer": 293,
		"Asteroid Blood Raiders Frigate": 116,
		"Mission Minmatar Republic Cruiser": 133,
		"Deadspace Serpentis Battleship": 221,
		"Deadspace Sansha's Nation Frigate": 213,
		"Rogue Drone": 123,
		"Asteroid Rogue Drone Commander Frigate": 339,
		"Asteroid Angel Cartel Commander Cruiser": 171,
		"Mission Container": 44,
		"FW Caldari State Frigate": 383,
		"Asteroid Sansha's Nation BattleCruiser": 281,
		"Asteroid Guristas Commander Battleship": 180,
		"Deadspace Overseer's Structure": 223,
		"Asteroid Angel Cartel Commander Frigate": 170,
		"FW Amarr Empire Destroyer": 387,
		"FW Amarr Empire Cruiser": 391,
		"Mission Faction Cruiser": 54,
		"Asteroid Serpentis Commander Cruiser": 186,
		"Police Drone": 109,
		"Asteroid Rogue Drone Commander BattleCruiser": 336,
		"Billboard": 125,
		"Pirate Drone": 159,
		"Asteroid Sansha's Nation Commander Battleship": 183,
		"Deadspace Sleeper Emergent Defender": 372,
		"Asteroid Serpentis Commander Destroyer": 286,
		"Asteroid Blood Raiders BattleCruiser": 272,
		"Deadspace Sleeper Awakened Patroller": 368,
		"Asteroid Rogue Drone Swarm": 315,
		"Asteroid Serpentis Hauler": 192,
		"Mission Faction Industrials": 75,
		"Mission CONCORD Cruiser": 202,
		"Asteroid Serpentis Destroyer": 284,
		"Tutorial Drone": 37,
		"Asteroid Guristas Commander Destroyer": 278,
		"Incursion Sansha's Nation Cruiser": 51,
		"Deadspace Guristas Cruiser": 132,
		"Faction Drone": 95,
		"Asteroid Blood Raiders Commander Cruiser": 175,
		"LCO Drone": 82,
		"Asteroid Serpentis Officer": 189,
		"Large Collidable Structure": 77,
		"Deadspace Angel Cartel Battleship": 218,
		"Deadspace Sleeper Emergent Patroller": 371,
		"Deadspace Serpentis Destroyer": 47,
		"Storyline Mission Cruiser": 254,
		"Asteroid Blood Raiders Destroyer": 273,
		"Asteroid Sansha's Nation Commander BattleCruiser": 283,
		"Deadspace Sleeper Awakened Sentinel": 370,
		"Mission Minmatar Republic Battlecruiser": 303,
		"Mission Faction Frigate": 355,
		"Mission Faction Transports": 74,
		"Mission Gallente Federation Destroyer": 308,
		"Mission Minmatar Republic Frigate": 134,
		"Mission Caldari State Destroyer": 306,
		"Mission Mordu Frigate": 198,
		"Asteroid Guristas Commander Cruiser": 178,
		"Asteroid Rogue Drone Commander Battleship": 335,
		"Deadspace Sleeper Sleepless Defender": 366,
		"Mission Thukker Cruiser": 292,
		"Mission Gallente Federation Cruiser": 137,
		"Deadspace Sansha's Nation BattleCruiser": 299,
		"Concord Drone": 94,
		"FW Amarr Empire Battlecruiser": 395,
		"Storyline Cruiser": 252,
		"Mission Amarr Empire Carrier": 331,
		"Capture Point": 354,
		"Asteroid Guristas BattleCruiser": 277,
		"Asteroid Angel Cartel BattleCruiser": 269,
		"Asteroid Serpentis Commander BattleCruiser": 287,
		"Deadspace Blood Raiders Cruiser": 140,
		"Asteroid Angel Cartel Frigate": 57,
		"Deadspace Rogue Drone Destroyer": 289,
		"Mission Minmatar Republic Battleship": 78,
		"Sentry Gun": 30,
	},
	"Placeables": {
		"Furniture": 96,
	},
	"Sovereignty Structures": {
		"Sovereignty Blockade Units": 376,
		"Infrastructure Hubs": 377,
		"Territorial Claim Units": 375,
	},
	"Charge": {
		"Survey Probe": 241,
		"Cruise Missile": 8,
		"Advanced Torpedo": 68,
		"Torpedo": 13,
		"FoF Light Missile": 14,
		"Citadel Torpedo": 238,
		"Bomb ECM": 342,
		"Advanced Autocannon Ammo": 166,
		"Advanced Rocket": 69,
		"Light Defender Missile": 378,
		"Projectile Ammo": 7,
		"Advanced Heavy Assault Missile": 67,
		"Heavy Assault Missile": 249,
		"Festival Charges": 301,
		"Advanced Cruise Missile": 65,
		"FoF Heavy Missile": 34,
		"Citadel Cruise": 49,
		"Light Missile": 10,
		"Advanced Heavy Missile": 66,
		"Scanner Probe": 360,
		"Interdiction Probe": 266,
		"Bomb": 341,
		"Rocket": 12,
		"Bomb Energy": 343,
		"FoF Cruise Missile": 35,
		"Heavy Defender Missile": 11,
		"Advanced Light Missile": 64,
		"Heavy Missile": 9,
	},
	"Station": {
		"Station": 6,
	},
	"Special Edition Assets": {
		"Festival Charges Expired": 243,
	},
	"Orbitals": {
		"Orbital Infrastructure": 55,
		"Orbital Construction Platform": 98,
		"Test Orbitals": 86,
	},
	"Ship": {
		"Jump Freighter": 353,
		"Destroyer": 209,
		"Assault Frigate": 70,
		"Attack Battlecruiser": 103,
		"Dreadnought": 245,
		"Supercarrier": 85,
		"Shuttle": 29,
		"Freighter": 248,
		"Capital Industrial Ship": 348,
		"Marauder": 352,
		"Stealth Bomber": 129,
		"Exhumer": 262,
		"Capsule": 27,
		"Heavy Interdiction Cruiser": 154,
		"Electronic Attack Ship": 127,
		"Industrial Command Ship": 350,
		"Covert Ops": 126,
		"Blockade Runner": 164,
		"Frigate": 22,
		"Deep Space Transport": 165,
		"Black Ops": 259,
		"Strategic Cruiser": 359,
		"Prototype Exploration Ship": 45,
		"Force Recon Ship": 151,
		"Rookie ship": 23,
		"Interdictor": 261,
		"Logistics": 153,
		"Industrial": 26,
		"Cruiser": 24,
		"Command Ship": 260,
		"Battleship": 25,
		"Titan": 28,
		"Carrier": 291,
		"Combat Recon Ship": 152,
		"Combat Battlecruiser": 91,
		"Heavy Assault Cruiser": 71,
		"Interceptor": 128,
		"Mining Barge": 233,
	},
	"Deployable": {
		"Mobile Warp Disruptor": 155,
		"Mobile Jump Disruptor": 106,
	},
	"Structure": {
		"Moon Mining": 206,
		"Assembly Array": 195,
		"Corporate Hangar Array": 235,
		"Refining Array": 157,
		"Target Painting Battery": 347,
		"Mobile Hybrid Sentry": 215,
		"Stealth Emitter Array": 239,
		"Force Field Array": 229,
		"Mobile Shield Generator": 208,
		"Shield Hardening Array": 228,
		"Energy Neutralizing Battery": 326,
		"Mobile Power Core": 205,
		"Stasis Webification Battery": 225,
		"Mobile Storage": 158,
		"Cynosural System Jammer": 328,
		"Electronic Warfare Battery": 224,
		"Silo": 196,
		"Cynosural Generator Array": 327,
		"Structure Repair Array": 330,
		"Mobile Projectile Sentry": 214,
		"Control Tower": 105,
		"Mobile Laser Sentry": 216,
		"Ship Maintenance Array": 156,
		"Personal Hangar": 400,
		"Sensor Dampening Battery": 226,
		"Mobile Laboratory": 204,
		"Warp Scrambling Battery": 227,
		"Jump Portal Array": 104,
		"Mobile Reactor": 217,
		"Mobile Missile Sentry": 207,
		"Tracking Array": 236,
		"Scanner Array": 329,
	},
};
